<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>try…catch…finally命令</title>
</head>
<body>
<script type="text/javascript">

/////////////////////////////////////////////////////////////////////////////
//  try {
//   例外が発生するかもしれない命令(群)
//  } catch (例外情報を受け取る変数) {
//   例外が発生した時の命令(群)
//  }[finally {
//   例外の有無に関わらず、最終的に実行される命令(群)
//  }]
/////////////////////////////////////////////////////////////////////////////

var i = 1;
try {
  i = i * j; //例外発生
} catch (e) {
  document.writeln(e.message);
} finally {
  document.writeln('処理は完了しました。');
}

//throw命令
//throw new Error(エラーメッセージ)
var x = 1;
var y = 0;
try {
  if (y == 0) { throw new Error('0で除算しようとしました。'); }
  var z = x / y;
} catch (e) {
  document.writeln(e.message);
}
</script>
</body>
</html>
